full: meres02.tex
	pdflatex -interaction=nonstopmode -halt-on-error meres02.tex > output.txt
	pdflatex -interaction=nonstopmode -halt-on-error meres02.tex >> output.txt
	rm -f meres02.aux meres02.bbl meres02.blg meres02.out meres02.log meres02.toc meres02.xmpdata pdfa.xmpi texput.log
